version: 2

models:

  - name: stg_customers
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null

      - name: email
        tests:
          - not_null

  - name: stg_products
    columns:
      - name: product_id
        tests:
          - unique
          - not_null

  - name: stg_orders
    columns:
      - name: order_id
        tests:
          - unique
          - not_null

      - name: customer_id
        tests:
          - not_null
          
  - name: fact_sales
    columns:

      - name: customer_id
        tests:
          - relationships:
              to: ref('dim_customer')
              field: customer_id

      - name: product_id
        tests:
          - relationships:
              to: ref('dim_product')
              field: product_id

      - name: store_id
        tests:
          - relationships:
              to: ref('dim_store')
              field: store_id