retail_dbt:
  target: ci

  outputs:
    ci:
      type: snowflake
      account: MKKDCUL-RL41122
      user: VEERESH123
      password: Veereshkumar@135
      database: retail_db
      schema: raw
      warehouse: Veeresh
      role: ACCOUNTADMIN
      threads: 4