retail_dbt:
  target: dev

  outputs:

    dev:

      type: snowflake

      account: MKKDCUL-RL41122

      user: VEERESH123

      password: Veereshkumar@135

      role: ACCOUNTADMIN

      database: retail_db

      warehouse: Veeresh

      schema: v_stg

      threads: 4

      client_session_keep_alive: False