name: Retail Data Pipeline CI

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - main
      - develop


jobs:

  # ==========================================
  # JOB 1: Validate Python and Airflow code
  # ==========================================

  python-validation:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"


      - name: Check Python version
        run: python --version


      - name: Validate Python files
        run: |
          python -m compileall airflow
          python -m compileall run_validation.py


  # ==========================================
  # JOB 2: Validate dbt project
  # ==========================================

  dbt-validation:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"


      - name: Install dbt
        run: |
          pip install dbt-core==1.12.0
          pip install dbt-snowflake==1.12.0


      - name: Check dbt version
        run: |
          dbt --version


      - name: Install dbt dependencies
        working-directory: retail_dbt
        run: |
          dbt deps


      - name: Parse dbt project
        working-directory: retail_dbt
        run: |
          dbt parse